version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  pharmacy-recommendation-redis:                        # 서비스명
    container_name: pharmacy-recommendation-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: zcx5674/pharmacy-recommendation-redis
    ports:
      - "6379:6379"